# Generated by Django 2.2 on 2019-04-16 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='centermaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='shiftcutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='shiftmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('centerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='djangorest.centermaster')),
                ('cutoffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='djangorest.shiftcutoff')),
            ],
        ),
        migrations.CreateModel(
            name='scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('centerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='djangorest.centermaster')),
                ('shiftid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='djangorest.shiftcutoff')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
